/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jeon' at '16. 11. 3 오후 7:05' with Gradle 2.14.1
 *
 * @author Jeon, @date 16. 11. 3 오후 7:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
